### ISSUE TITLE
Issue while getting Args when variables are directly passed

### ISSUE THREAD

**Issue by huzaifaali14** [smeijer/graphql-args#3]
astToBody function not returning nested object due to which `getArgs` function skips some of the argument values

<img width="475" alt="Screenshot 2023-02-11 at 10 48 10 AM" src="https://user-images.githubusercontent.com/30002668/218242796-3983fe31-cf09-405e-ae60-5a66318d17b8.png">

This is what my mutation looks like

`mutation UpdateUser {
  updateUser(id: "8b068c9e-04a0-446b-87cc-07e065f550ef", user:{
    userRoles: [ADMIN]
  }){
    id
  }
}`

**Comment by smeijer** [comment]
Fixed by #4
